'use client';
import {useEffect,useState} from 'react';
import {NortePIcon as Icon} from '../nortep-icons';
import {number} from './model';
import type {CandidateEntry,Catalog} from './elections';
export default function CandidateSearch({catalog,onChoose}:{catalog:Catalog;onChoose:(c:CandidateEntry,municipality:string)=>void}){
 const[name,setName]=useState(''),[year,setYear]=useState(''),[office,setOffice]=useState(''),[municipality,setMunicipality]=useState('');
 const[submitted,setSubmitted]=useState(''),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[found,setFound]=useState<{items:CandidateEntry[];total:number;pageSize:number}|null>(null);
 const begin=()=>{setBusy(true);setError('');setFound(null);};
 useEffect(()=>{if(!submitted)return;const controller=new AbortController();const p=new URLSearchParams(submitted);p.set('pagina',String(page));void fetch('/api/analise-eleitoral/dados?'+p,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(30000)])}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);return b;}).then(b=>{if(!controller.signal.aborted)setFound(b);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível buscar.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[submitted,page,attempt]);
 const offices=[...new Map(catalog.events.filter(e=>!year||String(e.year)===year).map(e=>[e.officeId,e.office])).entries()].sort((a,b)=>+a[0]-+b[0]);
 return <section className="ea-find" aria-label="Busca em Minas Gerais"><div className="ea-section-heading"><div><span className="ea-eyebrow">VOCÊ ESCOLHE QUEM CONSULTAR</span><h2>Qual candidato você quer conhecer?</h2><p>Digite um nome ou use os filtros para encontrar a eleição.</p></div><Icon name="search" size={30}/></div>
 <form onSubmit={e=>{e.preventDefault();if(name.trim().length<2&&!year&&!office&&!municipality){setError('Digite pelo menos duas letras ou escolha um filtro.');return;}begin();setPage(1);setAttempt(v=>v+1);setSubmitted(new URLSearchParams({modo:'busca',q:name,ano:year,cargo:office,cidade:municipality}).toString());}}><label className="ea-find-name">Nome, número ou partido<input value={name} onChange={e=>setName(e.target.value)} placeholder="Digite o candidato que você quer consultar" maxLength={120}/></label><div className="ea-find-filters"><label>Ano<select value={year} onChange={e=>{setYear(e.target.value);setOffice('');}}><option value="">2022 e 2024</option><option>2022</option><option>2024</option></select></label><label>Cargo<select value={office} onChange={e=>setOffice(e.target.value)}><option value="">Todos os cargos</option>{offices.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Município da busca<select value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="">Toda Minas Gerais</option>{catalog.municipalities.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button type="submit" className="ea-primary"><Icon name="search" size={18}/>Buscar candidatos</button></div></form>
 {busy&&<p role="status">Buscando nos resultados oficiais…</p>}{error&&<p role="alert">{error}</p>}{found&&<div className="ea-found"><p role="status">{number(found.total)} candidaturas encontradas.</p>{found.items.map(c=>{const event=catalog.events.find(e=>e.id===c.eventId)!;const place=c.municipalityId==='MG'?'Minas Gerais':catalog.municipalities.find(m=>m.id===c.municipalityId)?.name;return <button className="ea-found-row" key={c.eventId+':'+c.id} onClick={()=>onChoose(c,new URLSearchParams(submitted).get('cidade')||'')}><span className="ea-candidate-initials">{c.number}</span><span><strong>{c.name}</strong><small>{event.office} · {event.year} · {event.round}º turno · {c.party}</small><small>{place}</small></span><Icon name="chevron" size={19}/></button>;})}{found.total===0&&<div className="ea-empty compact"><h3>Nenhum candidato encontrado.</h3><p>Confira o nome ou tente outro cargo, ano ou município.</p></div>}{found.total>found.pageSize&&<div className="ea-pagination"><button disabled={page===1} onClick={()=>{begin();setPage(p=>p-1);}}>Anterior</button><span>Página {page} de {Math.ceil(found.total/found.pageSize)}</span><button disabled={page*found.pageSize>=found.total} onClick={()=>{begin();setPage(p=>p+1);}}>Próxima</button></div>}</div>}
 <p className="ea-search-note">Resultados históricos de 2022 e 2024. Presidente, governador, senador, deputados, prefeito e vereador, conforme o ano. Para presidente, os votos exibidos são os de Minas Gerais.</p></section>;
}
