'use client';
import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';
import {NortePIcon as Icon,type IconName} from '../nortep-icons';
import {electoralAccess,type Access} from './access';
import {csvCell,normalize,number,percent,queryUrl,ratio} from './model';
import {contestId,readQuery,savedQueries,type CandidateEntry,type Catalog,type ElectoralQuery,type Result,type Saved} from './elections';
import CandidateSearch from './candidate-search';
import CandidateProfile from './candidate-profile';
import TerritoryPanel from './territory-panel';
import './electoral.css';
type Section='inicio'|'consulta'|'salvas'|'fontes';
type Tab='resultado'|'perfil'|'territorio'|'comparar';
const nav:{id:Section;label:string;icon:IconName}[]=[{id:'inicio',label:'Buscar candidatos',icon:'search'},{id:'consulta',label:'Minha análise',icon:'chart'},{id:'salvas',label:'Minhas consultas',icon:'bookmark'},{id:'fontes',label:'Sobre os dados',icon:'shield'}];
const title=(s:string)=>s.toLocaleLowerCase('pt-BR').replace(/(^|\s)\S/g,c=>c.toLocaleUpperCase('pt-BR'));
export default function ElectoralApp(){
 const[access,setAccess]=useState<Access|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const[section,setSection]=useState<Section>('inicio'),[tab,setTab]=useState<Tab>('resultado'),[menu,setMenu]=useState(false);
 const[query,setQuery]=useState<ElectoralQuery|null>(null),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[resultError,setResultError]=useState('');
 const[saved,setSaved]=useState<Saved[]>([]),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[saveName,setSaveName]=useState(''),[copyUrl,setCopyUrl]=useState('');
 const[filter,setFilter]=useState(''),[party,setParty]=useState(''),[page,setPage]=useState(1),[areaFilter,setAreaFilter]=useState(''),[areaPage,setAreaPage]=useState(1);
 const saveInput=useRef<HTMLInputElement>(null),profileId=access?.profile.id,storageKey=access?`nortep-eleitoral-consultas-v1:${access.profile.id}`:'';
 useEffect(()=>{let alive=true;void(async()=>{try{const a=await electoralAccess();if(!alive)return;setAccess(a);if(!a.allowed)return;const r=await fetch('/api/analise-eleitoral/dados',{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Não foi possível carregar as eleições.');const c=await r.json() as Catalog;if(c.schemaVersion!==2)throw Error('Atualize a página para abrir a nova consulta.');if(!alive)return;setCatalog(c);const params=new URLSearchParams(window.location.search);if(params.has('eleicao')){const q=readQuery(params);setBusy(true);setResult(null);setResultError('');setQuery(q);setSection('consulta');setTab(q.candidateIds.length===2?'comparar':'resultado');}if(!a.preview){try{setSaved(savedQueries(localStorage.getItem(`nortep-eleitoral-consultas-v1:${a.profile.id}`),c));}catch{setNotice('O navegador não permitiu abrir suas consultas salvas.');}}}catch(e){if(alive)setError(e instanceof Error?e.message:'Não foi possível abrir o NorteP.');}})();return()=>{alive=false;};},[attempt]);
 useEffect(()=>{if(!profileId)return;let alive=true;const check=async()=>{try{const a=await electoralAccess();if(!alive)return;if(a.profile.id!==profileId){setCatalog(null);setResult(null);setQuery(null);setSaved([]);setAccess(null);setAttempt(v=>v+1);}else{setAccess(a);if(!a.allowed){setCatalog(null);setResult(null);setSaved([]);}}}catch(e){if(alive){setCatalog(null);setResult(null);setSaved([]);setError(e instanceof Error?e.message:'Entre novamente.');}}};const storage=(e:StorageEvent)=>{if(e.key==='nortep-sessao'||e.key===null)void check();};window.addEventListener('focus',check);window.addEventListener('storage',storage);const interval=window.setInterval(check,60000);return()=>{alive=false;clearInterval(interval);window.removeEventListener('focus',check);window.removeEventListener('storage',storage);};},[profileId]);
 useEffect(()=>{if(!query||!catalog||!access?.allowed)return;const controller=new AbortController();void fetch('/api/analise-eleitoral/dados?'+queryUrl(query).split('?')[1],{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(45000)])}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);return b as Result;}).then(b=>{if(!controller.signal.aborted){setResult(b);if(query.candidateIds.some(id=>!b.query.candidateIds.includes(id)))setNotice('Um candidato do link não pertence a esta eleição. Confira a seleção.');}}).catch(e=>{if(!controller.signal.aborted)setResultError(e instanceof Error?e.message:'Não foi possível carregar a consulta.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[query,catalog,access?.allowed]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[section]);useEffect(()=>{if(saving)saveInput.current?.focus();},[saving]);
 const back=access?.preview?'/?abrir=visoes':'/?abrir=ecossistema';
 const loginHref=(channel:string)=>{const p=new URLSearchParams({acesso:channel,continuar:'analise-eleitoral'});if(typeof window!=='undefined')for(const key of ['eleicao','zona','candidato'])for(const v of new URLSearchParams(window.location.search).getAll(key).slice(0,2))p.append(key,v.slice(0,80));return '/?'+p;};
 const go=(s:Section)=>{setSection(s);setMenu(false);setSaving(false);setCopyUrl('');setNotice('');};
 const open=(q:ElectoralQuery,t:Tab='resultado')=>{setBusy(true);setResult(null);setResultError('');setPage(1);setAreaPage(1);setAreaFilter('');setSaving(false);setCopyUrl('');setQuery(q);setTab(t);go('consulta');setFilter('');setParty('');};
 const choose=(c:CandidateEntry,mid:string)=>{const e=catalog!.events.find(e=>e.id===c.eventId)!;open({contestId:contestId(e,e.statewide?(mid||'MG'):c.municipalityId),zone:'all',candidateIds:[c.id],search:'',party:'all'});};
 const persist=(items:Saved[])=>{if(access?.preview)return false;try{localStorage.setItem(storageKey,JSON.stringify(items));setSaved(items);return true;}catch{setNotice('Não foi possível salvar neste navegador.');return false;}};
 const selected=result?.query.candidateIds.flatMap(id=>{const c=result.candidates.find(c=>c.id===id);return c?[c]:[];})||[];
 const scope=result?`${result.event.office} · ${result.event.year} · ${result.event.round}º turno · ${title(result.municipality)}${result.query.zone!=='all'?` · Zona ${result.query.zone}`:''}`:'';
 const save=(e:React.FormEvent)=>{e.preventDefault();if(!result||!catalog||!saveName.trim()||access?.preview)return;if(saved.length>=50){setNotice('Remova uma consulta para salvar outra. O limite é de 50.');return;}if(persist([{id:crypto.randomUUID(),name:saveName.trim().slice(0,100),savedAt:new Date().toISOString(),datasetVersion:catalog.version,query:result.query},...saved])){setSaving(false);setNotice('Consulta salva em Minhas consultas.');}};
 const visible=result?.candidates.filter(c=>(!party||c.party===party)&&normalize(`${c.name} ${c.fullName} ${c.number} ${c.party}`).includes(normalize(filter)))||[];
 const areas=result?.areas.filter(a=>normalize(a.name).includes(normalize(areaFilter)))||[];
 const exportCsv=()=>{if(!catalog||!result)return;const rows:(string|number)[][]=[['Fonte','TSE',`https://dadosabertos.tse.jus.br/dataset/resultados-${result.event.year}`],['Versão',catalog.version],['Recorte',scope],['Código município TSE',result.municipalityId],['Código IBGE',result.territory?.ibgeId||''],['Ano de referência',result.event.year],['Base dos percentuais',result.totals.valid],['Candidato','Número','Partido','Votos válidos','Percentual dos válidos','Situação na eleição']];for(const c of selected.length?selected:visible)rows.push([c.name,c.number,c.party,c.votes,percent(c.percentage),c.status]);if(selected.length&&result.areas.length){rows.push([],['Distribuição territorial','Código TSE ou zona',...selected.map(c=>c.name),'Votos válidos do recorte']);for(const a of result.areas)rows.push([a.name,a.id,...a.votes,a.total]);}const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`nortep-${result.event.year}-${result.event.officeId}-${result.municipalityId}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Arquivo preparado com fonte, ano e códigos do território.');};
 const copy=async()=>{if(!result)return;const url=window.location.origin+queryUrl(result.query);try{await navigator.clipboard.writeText(url);setNotice('Link copiado. A consulta abre com o acesso NorteP de quem receber.');}catch{setCopyUrl(url);}};
 if(error||(access&&!access.allowed))return <main className="ea ea-gate"><Image src="/nortep-icon-v1.png" alt="NorteP" width={64} height={64}/><span className="ea-eyebrow">ANÁLISE ELEITORAL</span><h1>{access&&!access.allowed?'Um acesso para cada função.':'Vamos continuar?'}</h1><p role="alert">{error||`A análise eleitoral não está disponível para este perfil${access?.preview?`: ${access.previewLabel}`:''}.`}</p><div className="ea-actions"><a className="ea-primary" href={back}>Voltar ao NorteP</a>{error&&<button onClick={()=>{setError('');setAccess(null);setCatalog(null);setAttempt(v=>v+1);}}>Tentar novamente</button>}</div>{error&&<div className="ea-login-options"><p>Entre pelo seu acesso:</p>{[['principal','Administração principal'],['administracao','Administração'],['coordenacao','Coordenação'],['supervisao','Supervisão'],['observador','Observador']].map(([key,label])=><a key={key} href={loginHref(key)}>{label}</a>)}</div>}</main>;
 if(!catalog||!access)return <main className="ea ea-gate" aria-busy="true"><Icon name="compass" size={48}/><h1>Abrindo sua análise.</h1><p role="status">Conferindo seu acesso e carregando as eleições.</p></main>;
 return <div className="ea ea-shell"><a className="ea-skip" href="#eleitoral-conteudo">Ir para o conteúdo</a>{menu&&<button className="ea-scrim" aria-label="Fechar menu" onClick={()=>setMenu(false)}/>}
 <aside className={`ea-sidebar ${menu?'is-open':''}`}><a className="ea-brand" href={back}><Image src="/nortep-icon-v1.png" alt="" width={40} height={40}/><span>NorteP<small>Análise Eleitoral</small></span></a><p className="ea-nav-label">SEU ESPAÇO DE ANÁLISE</p><nav aria-label="Análise eleitoral">{nav.map(n=><button key={n.id} className={section===n.id?'is-active':''} aria-current={section===n.id?'page':undefined} onClick={()=>go(n.id)}><Icon name={n.icon}/>{n.label}{n.id==='salvas'&&saved.length>0&&<span className="ea-count">{saved.length}</span>}</button>)}</nav><div className="ea-side-bottom"><div className="ea-source-small"><Icon name="shield"/><div><strong>Informação com origem</strong><p>Dados do TSE e do IBGE, com fonte e período visíveis.</p></div></div><a className="ea-back" href={back}><Icon name="back"/>{access.preview?'Voltar à visão completa':'Voltar ao ecossistema'}</a></div></aside>
 <div className="ea-main"><header className="ea-header"><div><button className="ea-menu-button" aria-label="Abrir menu" onClick={()=>setMenu(true)}><Icon name="menu"/></button><span>Ecossistema NorteP <span className="ea-header-slash">/</span><strong>Análise Eleitoral</strong></span></div><span className="ea-account"><span className="ea-avatar">{access.profile.name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('')}</span>{access.profile.name.split(' ')[0]}</span></header><main id="eleitoral-conteudo" className="ea-content">
 {access.preview&&<div className="ea-preview"><Icon name="info"/><span><strong>Prévia: {access.previewLabel}.</strong> Você pode consultar e comparar. Nenhuma consulta será gravada nesta prévia.</span><a href={back}>Voltar</a></div>}{notice&&<div className="ea-notice" role="status"><Icon name="info"/><span>{notice}</span><button aria-label="Fechar aviso" onClick={()=>setNotice('')}><Icon name="close" size={17}/></button></div>}{copyUrl&&<label className="ea-copy">Endereço da consulta<input readOnly value={copyUrl} onFocus={e=>e.target.select()}/></label>}
 {section==='inicio'&&<><section className="ea-hero"><div><span className="ea-eyebrow"><span className="ea-dot"/>MINAS GERAIS · 2022 E 2024</span><h1>Escolha um nome.<br/><em>Conheça os resultados.</em></h1><p>Candidatos, votos e territórios em uma consulta clara. Você escolhe por onde começar.</p><div className="ea-hero-note"><Icon name="shield" size={17}/>Dados oficiais. Fontes sempre à vista.</div></div><div className="ea-hero-art" aria-hidden="true"><div className="ea-orbit ea-orbit-one"/><div className="ea-orbit ea-orbit-two"/><div className="ea-art-center"><Icon name="compass" size={110}/></div><div className="ea-art-card"><Icon name="chart" size={28}/><span>UM OLHAR PARA MINAS<strong>853</strong>MUNICÍPIOS</span></div></div></section><CandidateSearch catalog={catalog} onChoose={choose}/></>}
 {section==='consulta'&&<><div className="ea-page-heading"><span className="ea-eyebrow">SUA CONSULTA ELEITORAL</span><h1>{selected.length===1?selected[0].name:tab==='comparar'?'Dois candidatos, a mesma base.':'Conheça os resultados.'}</h1><p>{result?scope:'Busque um candidato para começar.'}</p><button onClick={()=>go('inicio')}><Icon name="search" size={17}/>Nova busca</button></div>{busy&&<div className="ea-empty" role="status" aria-busy="true"><Icon name="compass" size={36}/><h2>Carregando sua consulta…</h2></div>}{resultError&&<div className="ea-empty"><p role="alert">{resultError}</p><button onClick={()=>query&&open({...query},tab)}>Tentar novamente</button><button onClick={()=>go('inicio')}>Fazer nova busca</button></div>}{!query&&!busy&&<CandidateSearch catalog={catalog} onChoose={choose}/>}
 {result&&!busy&&<><section className="ea-filters" aria-label="Filtros da consulta"><div className="ea-fixed-context"><Icon name="ballot"/><span><small>ELEIÇÃO</small><strong>{result.event.year} · {result.event.office}</strong></span></div><label>Município<select value={result.municipalityId} onChange={e=>open({...result.query,contestId:contestId(result.event,e.target.value),zone:'all',candidateIds:result.event.statewide?result.query.candidateIds:[]},tab)}>{result.event.statewide&&<option value="MG">Toda Minas Gerais</option>}{catalog.municipalities.filter(m=>result.event.municipalityIds.includes(m.id)).map(m=><option key={m.id} value={m.id}>{title(m.name)}</option>)}</select></label><label>Turno<select value={result.event.id} onChange={e=>{const event=catalog.events.find(v=>v.id===e.target.value)!;open({...result.query,contestId:contestId(event,result.municipalityId),zone:'all',candidateIds:[]},tab);}}>{catalog.events.filter(e=>e.year===result.event.year&&e.officeId===result.event.officeId&&(result.municipalityId==='MG'||e.municipalityIds.includes(result.municipalityId))).map(e=><option key={e.id} value={e.id}>{e.round}º turno</option>)}</select></label><label>Recorte<select value={result.query.zone} onChange={e=>open({...result.query,zone:e.target.value},tab)}><option value="all">{result.municipalityId==='MG'?'Todo o estado':'Todo o município'}</option>{result.zoneOptions.map(z=><option key={z} value={z}>Zona {z}</option>)}</select></label></section>
 <div className="ea-toolbar"><span className="ea-eyebrow">{result.event.officeId==='1'?'VOTOS EM MINAS GERAIS':'RESULTADOS OFICIAIS'}</span><div className="ea-actions"><button disabled={access.preview} onClick={()=>{setSaveName(selected.length?selected.map(c=>c.name).join(' × ')+' · '+result.event.year:scope);setSaving(true);}}><Icon name="bookmark"/>Salvar consulta</button><button onClick={()=>void copy()}><Icon name="arrow"/>Copiar link</button><button onClick={exportCsv}><Icon name="download"/>Baixar dados</button></div></div>{saving&&<form className="ea-save-form" onSubmit={save}><label>Nome da consulta<input ref={saveInput} value={saveName} onChange={e=>setSaveName(e.target.value)} maxLength={100} required/></label><button className="ea-primary" type="submit">Salvar neste navegador</button><button type="button" onClick={()=>setSaving(false)}>Cancelar</button></form>}
 <div className="ea-tabs" aria-label="Detalhes da análise">{([['resultado','Votação','ballot'],['perfil','Perfil do candidato','people'],['territorio','Eleitorado e território','pin'],['comparar','Comparar','compare']] as const).map(([id,label,icon])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={tab===id?'ea-primary':''}><Icon name={icon} size={19}/>{label}</button>)}</div>{tab==='perfil'&&<CandidateProfile result={result} selected={selected}/>} {tab==='territorio'&&<TerritoryPanel result={result}/>}
 {(tab==='resultado'||tab==='comparar')&&<><div className="ea-metrics"><article><span>Eleitorado na apuração</span><strong>{number(result.totals.electorate)}</strong><small>Pessoas aptas no recorte</small></article><article><span>Comparecimento</span><strong>{percent(ratio(result.totals.turnout,result.totals.electorate))}</strong><small>{number(result.totals.turnout)} compareceram</small></article><article><span>Votos válidos</span><strong>{number(result.totals.valid)}</strong><small>{['6','7','13'].includes(result.event.officeId)?'Nominais + votos de legenda':'Base dos percentuais'}</small></article><article><span>Abstenção</span><strong>{percent(ratio(result.totals.abstentions,result.totals.electorate))}</strong><small>{number(result.totals.abstentions)} ausentes</small></article></div>
 {tab==='comparar'&&<section className="ea-comparison"><h2>Selecione dois candidatos</h2><p>Mesma eleição, cargo, turno e território.</p><div className="ea-compare-selects">{[0,1].map(i=><label key={i}>Candidato {i+1}<select disabled={i===1&&!selected[0]} value={result.query.candidateIds[i]||''} onChange={e=>{const ids=[...result.query.candidateIds];ids[i]=e.target.value;open({...result.query,candidateIds:ids.filter(Boolean)},'comparar');}}><option value="">Selecione um candidato</option>{result.candidates.map(c=><option key={c.id} value={c.id} disabled={result.query.candidateIds[1-i]===c.id}>{c.name} · {c.party}</option>)}</select></label>)}</div></section>}
 {selected.length>0&&<section className="ea-comparison"><div className="ea-compare-cards">{selected.map((c,i)=><article key={c.id} className={i===1?'second':''}><span className="ea-candidate-initials">{c.number}</span><span>{c.party} · {c.status.startsWith('#')?'Não informada':title(c.status)}</span><h2>{c.name}</h2><strong>{number(c.votes)}</strong><small>votos válidos no recorte</small><b>{percent(c.percentage)}</b><div className="ea-bar-track"><span style={{width:`${c.percentage||0}%`}}/></div><p>{c.rank}ª posição por votos neste recorte</p></article>)}</div><div className="ea-explanation"><Icon name="info"/><p>{selected.length===2?<>A diferença é de <strong>{number(Math.abs(selected[0].votes-selected[1].votes))} votos válidos</strong> e <strong>{number(Math.round(Math.abs((selected[0].percentage||0)-(selected[1].percentage||0))*100)/100)} pontos percentuais</strong>. A base comum é de </>:<>O percentual de {selected[0].name} considera </>}{number(result.totals.valid)} votos válidos neste recorte.</p></div>{selected.length===1&&<div className="ea-actions"><button onClick={()=>setTab('perfil')}>Conhecer o perfil <Icon name="arrow" size={17}/></button><button className="ea-primary" onClick={()=>setTab('comparar')}><Icon name="compare"/>Comparar com outro candidato</button></div>}</section>}
 {selected.length>0&&result.areas.length>0&&<section className="ea-results"><div className="ea-results-heading"><h2>{result.municipalityId==='MG'?'Votos por município':'Votos por zona'}</h2><label>Buscar território<input value={areaFilter} onChange={e=>{setAreaFilter(e.target.value);setAreaPage(1);}} placeholder="Nome da cidade ou zona"/></label></div><div className="ea-table-scroll"><table><thead><tr><th>Território</th>{selected.map(c=><th key={c.id}>{c.name}</th>)}</tr></thead><tbody>{areas.slice((areaPage-1)*25,areaPage*25).map(a=><tr key={a.id}><th><button onClick={()=>open({...result.query,contestId:result.municipalityId==='MG'?contestId(result.event,a.id):result.query.contestId,zone:result.municipalityId==='MG'?'all':a.id},tab)}>{title(a.name)} <Icon name="chevron" size={15}/></button></th>{a.votes.map((v,i)=><td key={i} className="ea-numeric"><strong>{number(v)}</strong><span className="ea-row-detail">{percent(ratio(v,a.total))} dos válidos</span></td>)}</tr>)}</tbody></table></div>{!areas.length&&<p className="ea-empty compact">Nenhum território encontrado.</p>}<div className="ea-pagination"><button disabled={areaPage===1} onClick={()=>setAreaPage(p=>p-1)}>Anterior</button><span>{areas.length} territórios · Página {areaPage} de {Math.max(1,Math.ceil(areas.length/25))}</span><button disabled={areaPage*25>=areas.length} onClick={()=>setAreaPage(p=>p+1)}>Próxima</button></div></section>}
 <section className="ea-results"><div className="ea-results-heading"><h2>Candidatos <span>{result.candidates.length}</span></h2><div className="ea-table-filters"><label>Buscar nesta eleição<input placeholder="Buscar nome, número ou partido" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}/></label><label>Partido<select value={party} onChange={e=>{setParty(e.target.value);setPage(1);}}><option value="">Todos os partidos</option>{[...new Set(result.candidates.map(c=>c.party))].sort().map(p=><option key={p}>{p}</option>)}</select></label></div></div><div className="ea-table-scroll"><table><thead><tr><th>Candidato</th><th>Partido</th><th>Votos válidos</th><th>% dos válidos</th><th>Situação na eleição</th></tr></thead><tbody>{visible.slice((page-1)*25,page*25).map(c=><tr key={c.id}><th><button className="ea-name-button" onClick={()=>open({...result.query,candidateIds:[c.id]})}>{c.name} <Icon name="chevron" size={15}/></button><span className="ea-row-detail">Nº {c.number} · {c.rank}ª posição no recorte</span>{c.recorded!==c.votes&&<span className="ea-row-detail">{number(c.recorded)} votos registrados, incluindo não válidos.</span>}</th><td>{c.party}</td><td className="ea-numeric"><strong>{number(c.votes)}</strong></td><td>{percent(c.percentage)}</td><td>{c.status.startsWith('#')?'Não informada':title(c.status)}</td></tr>)}</tbody></table></div>{!visible.length&&<div className="ea-empty compact"><h3>Nenhum candidato encontrado.</h3><button onClick={()=>{setFilter('');setParty('');setPage(1);}}>Limpar busca</button></div>}<div className="ea-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{visible.length} candidatos · Página {page} de {Math.max(1,Math.ceil(visible.length/25))}</span><button disabled={page*25>=visible.length} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></section>
 <details className="ea-glossary"><summary>Entenda os números <Icon name="info" size={18}/></summary><dl><div><dt>Votos válidos e legenda</dt><dd>{number(result.totals.nominalValid)} votos nominais e {number(result.totals.partyValid)} votos de legenda. O percentual usa o total válido. Votos de legenda não são atribuídos a um candidato.</dd></div><div><dt>Outros votos</dt><dd>{number(result.totals.blank)} brancos; {number(result.totals.nullVotes)} nulos; {number(result.totals.annulled)} anulados; {number(result.totals.pending)} anulados sub judice; {number(result.totals.separate)} anulados apurados em separado.</dd></div><div><dt>Situação e posição</dt><dd>A situação vem da eleição original {result.event.officeId==='1'?'nacional':result.event.statewide?'em Minas Gerais':'no município'}. A posição considera os votos do recorte selecionado. Nos cargos proporcionais, a posição por votos não determina, sozinha, quem foi eleito.</dd></div></dl></details></>}
 </>}</>}
 {section==='salvas'&&<><div className="ea-page-heading"><span className="ea-eyebrow">SUAS ESCOLHAS, ORGANIZADAS</span><h1>Minhas consultas.</h1><p>Salvas neste navegador para sua conta.</p></div>{saved.length?<div className="ea-saved-list">{saved.map(s=><article key={s.id}><Icon name="bookmark"/><div><h2>{s.name}</h2><p>{new Date(s.savedAt).toLocaleDateString('pt-BR')}{s.datasetVersion!==catalog.version?' · Dados atualizados desde o salvamento':''}</p></div><button className="ea-primary" onClick={()=>open(s.query,s.query.candidateIds.length===2?'comparar':'resultado')}>Abrir <Icon name="arrow" size={18}/></button><button aria-label={`Remover consulta ${s.name}`} onClick={()=>persist(saved.filter(item=>item.id!==s.id))}><Icon name="trash" size={18}/></button></article>)}</div>:<div className="ea-empty"><Icon name="bookmark" size={36}/><h2>Sua próxima consulta pode ficar aqui.</h2><p>Escolha “Salvar consulta” ao abrir um resultado.</p><button onClick={()=>go('inicio')}>Buscar candidatos</button></div>}</>}
 {section==='fontes'&&<><div className="ea-page-heading"><span className="ea-eyebrow">TRANSPARÊNCIA EM CADA CONSULTA</span><h1>Você sabe de onde vem.</h1></div><section className="ea-source-card"><h2>TSE · Eleições de 2022 e 2024</h2><dl>{[['Cobertura','853 municípios de Minas. Presidente, governador, senador e deputados em 2022; prefeito e vereador em 2024. Turnos disponíveis nos arquivos oficiais.'],['Perfil do candidato','Dados declarados no registro daquela eleição. A situação histórica não confirma quem exerce mandato hoje.'],['Perfil do eleitorado','Distribuições separadas de gênero, idade e escolaridade do cadastro eleitoral. Não identificam o voto ou a preferência de uma pessoa ou grupo.'],['Contexto do IBGE','População, área e densidade do Censo 2022. Os códigos municipais do TSE e do IBGE são relacionados por uma tabela conferida para os 853 municípios.'],['Conferência','Votos nominais conferidos com os candidatos; votos de legenda preservados; comparecimento e abstenção conferidos com o eleitorado de cada zona.'],['Atualização',`Resultados gerados pelo TSE em ${catalog.source.generatedAt.join(' · ')}. Esta é uma versão dos dados, não uma apuração ao vivo ou projeção futura.`],['Leitura dos números','Busca, percentuais e comparações são calculados diretamente. Não há uma IA gerando explicações nesta versão.']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="ea-actions">{[2022,2024].map(y=><a className="ea-primary" key={y} href={`https://dadosabertos.tse.jus.br/dataset/resultados-${y}`} target="_blank" rel="noopener noreferrer">TSE {y} <Icon name="arrow" size={17}/></a>)}<a href="https://sidra.ibge.gov.br/tabela/4714" target="_blank" rel="noopener noreferrer">IBGE · Censo 2022</a></div></section></>}
 <footer className="ea-footer"><span>NorteP · Dados que aproximam.</span><a href={catalog.source.url} target="_blank" rel="noopener noreferrer">Fonte: Tribunal Superior Eleitoral <Icon name="arrow" size={14}/></a></footer></main></div></div>;
}
